services:
  postgres:
    image: postgres:15
    container_name: renewal-postgres
    environment:
      POSTGRES_DB: renewal
      POSTGRES_USER: aytan
      POSTGRES_PASSWORD: aytan01
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
